try:
    num=5/0
except:
    print("An ERROR occurred")
    raise ValueError